[Fix] Add Image Variable types
chili-publish/editor-sdk pull request #208
Opened 2022-11-23 11:50 UTC by pkgacek

This PR adds `src` to the `Variable` type. It is based of the FrameImage typing.

2022-11-23 14:23 UTC, alexandraFlavia9 requested changes

2022-11-23 14:23 UTC, alexandraFlavia9 commented on types/VariableTypes.ts
> +interface mediaConnectorImageVariableSource extends ImageVariableSource {
Capitalize it pls

2022-11-23 14:30 UTC, pkgacek commented on types/VariableTypes.ts
> +interface mediaConnectorImageVariableSource extends ImageVariableSource {
Done, sorry

2022-11-23 14:43 UTC, alexandraFlavia9 approved these changes

2022-11-24 12:11 UTC, abdelhalimkhouas approved these changes

2022-11-25 09:36 UTC, merged