[Feature] Refactor tests
chili-publish/editor-sdk pull request #256
Opened 2023-03-02 12:33 UTC by brapoprod

This PR refactors the tests

## Related tickets

-   [WRS-1103](https://support.chili-publish.com/projects/WRS/issues/WRS-1103)

## Screenshots

2023-03-06 16:24 UTC, pkgacek approved these changes

2023-03-07 16:26 UTC, NicolaVerbeeck approved these changes
![so-so-good](https://user-images.githubusercontent.com/7778415/223485124-1a19c62e-1259-4a3e-8711-a082fb99e006.gif)

2023-03-08 05:21 UTC, Matthiee requested changes
Looks good, I left some comments where the old "Should call all of the functions of child successfully" style was still used.

2023-03-08 05:21 UTC, Matthiee commented on src/tests/controllers/CharacterStyleController.test.ts
> +        expect(mockEditorApi.renameCharacterStyle).toHaveBeenCalledWith('5', 'name');
All tests are grouped.

2023-03-08 05:21 UTC, Matthiee commented on src/tests/controllers/ColorStyleController.test.ts
> +describe('ColorStyleController', () => {
The tests are grouped.

2023-03-08 05:21 UTC, Matthiee commented on src/tests/controllers/ConfigurationConnectorController.test.ts
> +        await mockedConfigurationController.setValue(configKey, configValue);
The tests are grouped.

2023-03-08 05:21 UTC, Matthiee commented on src/tests/controllers/ConnectorController.test.ts
> +        await mockedConnectorController.getState(connectorId);
The tests are grouped.

2023-03-08 05:21 UTC, Matthiee commented on src/tests/controllers/DebugController.test.ts
> +    it('Should call all of the Debug Functions of EditorAPI successfully', async () => {
The tests are grouped.

2023-03-08 05:21 UTC, Matthiee commented on src/tests/controllers/FrameController.test.ts
> +        await mockedFrameController.addFrame(FrameTypeEnum.image, 100, 100, 100, 100);
The tests are grouped.

2023-03-08 05:21 UTC, Matthiee commented on src/tests/controllers/LayoutController.test.ts
> +        await mockedFontController.getLayouts();
The tests are grouped.

2023-03-08 05:21 UTC, Matthiee commented on src/tests/controllers/SubscriberContoller.test.ts
> +        await mockedSubscriberController.onAnimationChanged(JSON.stringify(mockedAnimation));
The tests are grouped.

2023-03-08 05:21 UTC, Matthiee commented on src/tests/controllers/AnimationController.test.ts
> +describe('AnimationController', () => {
The tests are grouped.

2023-03-08 08:55 UTC, alexandraFlavia9 approved these changes

2023-03-08 12:08 UTC, Matthiee approved these changes
LGTM, great work @brapoprod !

2023-03-08 12:09 UTC, NicolaVerbeeck approved these changes

2023-03-08 12:48 UTC, alexandraFlavia9 approved these changes

2023-03-08 14:17 UTC, merged