[Fix] Shape appearance is not inherited
chili-publish/editor-sdk pull request #258
Opened 2023-03-04 22:12 UTC by Dvergar

This PR makes shape appearance properties not inherited anymore

## Related tickets

-   [EDT-848](https://support.chili-publish.com/browse/EDT-848)

Can be tested against https://studio-dev.chiligrafx.com/?workspace=latest&engine=115 via `await SDK.frame.setShapeFrameFillColor('8', { "color": { "colorType": "rgb", "r": 0, "g": 250, "b": 51 }, "usageType": "local" });`

_I'm on holiday from the 6th to 10th of March, if a change is needed, better to contact the team._

2023-03-06 16:15 UTC, pkgacek approved these changes

2023-03-07 08:11 UTC, pkgacek submitted a review, later dismissed

2023-03-07 16:32 UTC, NicolaVerbeeck submitted a review, later dismissed
Looks good to me. Please wait and update this PRs tests once #256 has been merged. Sorry

2023-03-08 05:09 UTC, Matthiee submitted a review, later dismissed

2023-03-08 16:00 UTC, brapoprod requested changes
Please fix conflicts

2023-03-09 09:56 UTC, brapoprod submitted a review, later dismissed

2023-03-09 10:02 UTC, Matthiee submitted a review, later dismissed

2023-03-10 15:04 UTC, pkgacek requested changes
Pls conflicts

2023-03-13 08:17 UTC, brapoprod approved these changes

2023-03-13 13:34 UTC, Matthiee approved these changes

2023-03-13 14:23 UTC, pkgacek approved these changes

2023-03-13 14:25 UTC, merged